### ISSUE TITLE
Provide project card as a seperate page that can be embedded

### ISSUE THREAD

**Issue by kasbah** [kitspace/kitspace#282]
For instance @pyr0ball would like to show off their projects on their own website. We should build a html page for just the card, as it appears in the search, and make sure the server allows embedding it somewhere else using `<iframe>`. Gifycat may be a good example to look at for an existing implementation.

**Comment by pyr0ball** [comment]
So far what I've come up with (completely conceptual so far) is to have an HTML code block embedded in the page, and I'd need to add a custom CSS block that corresponds to that HTML block's class. As an example I pulled some source from kitspace.org to play with, but haven't yet had a chance to try implementing.

```html
<div class="boardCard">
	<a href="/boards/github.com/pyr0ball/pyr0piezo/Pyr0-Piezo Z-Probe Standalone Module">
		<div class="imgContainer">
			<img src="boards/github.com/pyr0ball/pyr0piezo/Pyr0-Piezo Z-Probe Standalone Module/images/top.png" class="img" style="transition: opacity 1s ease 0s; opacity: 1;">
		</div>
		<div class="title">Pyr0-Piezo Z-Probe Standalone Module</div>
		<div class="url">github.com / pyr0ball</div>
		<div class="summary">Standalone Pyr0-Piezo Circuit for using external arduino.</div>
	</a>
</div>
```

and the CSS block:

```css
.boardCard {
  border: 1px solid #cfcfcf;
  border-radius: 4px;
  cursor: pointer;
  display: inline-table;
  margin: 8px;
  overflow: hidden;
  width: 288px; }
  .boardCard a:hover {
    text-decoration: none; }
  .boardCard .imgContainer {
    background-color: #373737;
    padding-bottom: 16px;
    padding-top: 16px;
    height: 212px;
    vertical-align: middle;
    position: relative; }
  .boardCard .img {
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    margin: auto;
    max-width: 240px;
    max-height: 180px; }
  .boardCard .title {
    background-color: #fafafa;
    color: #373737;
    font-size: 18px;
    font-weight: bold;
    height: 40px;
    line-height: 40px;
    opacity: 1;
    padding-left: 10px;
    text-align: left;
    vertical-align: bottom;
    overflow: hidden;
    text-overflow: ellipsis;
    width: 286px;
    white-space: nowrap; }
  .boardCard .url {
    background-color: #fafafa;
    color: #808080;
    font-size: 13px;
    font-weight: normal;
    opacity: 1;
    padding-left: 10px;
    text-align: left; }
  .boardCard .summary {
    background-color: #fafafa;
    color: #373737;
    font-size: 16px;
    font-weight: normal;
    height: 96px;
    margin-bottom: 10px;
    opacity: 1;
    overflow: hidden;
    padding: 8px 10px 5px;
    text-align: left;
    vertical-align: top;
    visibility: visible; }
```
